version: "1.0"

services:
  db:
    image: mysql:5.7.44
    volumes:
      - db_data:/var/lib/mysql
    environment:
           MYSQL_ROOT_PASSWORD: open
           MYSQL_DATABASE: osm
           MYSQL_USER: osm
           MYSQL_PASSWORD: osm
    command: --sort_buffer_size=2M
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openstamanager
    volumes:
      - app_data:/var/www/html
    ports:
      - "8080:80"
    links:
      - db

volumes:
    db_data:
    app_data:
